### PR TITLE
Fetch attachments in Connector and pass to Zotero on save

### LINKED ISSUE #414: Saving to server doesn't work on PDFs
https://forums.zotero.org/discussion/101314/zotero-connector-not-saving-pdfs

Not totally sure why we don't allow this, but I guess we should — as I say there, we do allow it on iOS, where PDF metadata retrieval also isn't available. Here it's a bit more likely to just be a mistake, but I'm not sure that's a reason not to support this one feature when we support other things.

### PR DESCRIPTION
**Pull request by adomasven**
Changes the Zotero Connector so that attachments (PDF, etc) are downloaded in the connector with a background fetch and passed directly to Zotero. The Zotero Connector is backwards compatible with older Zotero versions which do not support receiving attachments from the Connector (new version of Zotero will not be backwards compatible with old connectors).

Supports advanced captcha handling (under whitelist, currently only sciencedirect.com), where if a PDF fetch fails we will load the pdf in a hidden frame and intercept upon content-disposition: attachment and then refetch with xhr. If hidden iframe fails, we pop open a window for the user to solve the captcha, and once again intercept and refetch with xhr. Seems to work very well. This is not supported on Safari, and we will still want to keep the captcha handling code in Zotero too (for magic wand, etc).

Generally means that attachment saving when access is provided by a proxy will now work in pretty much every case, since we don't need to pass credentials to Zotero and pretend we are the user's browser there.

Also fixed attachment saving to server.

Safari also needs: https://github.com/zotero/safari-app-extension/pull/7
Corresponding Zotero PR: https://github.com/zotero/zotero/pull/5148

Closes https://github.com/zotero/zotero-connectors/issues/474 , closes #414, closes https://github.com/zotero/zotero-connectors/issues/509

### CODE REVIEW

**Comment by adomasven** [comment]
This PR needs to be merged and deployed first (along with Safari changes). The Zotero PR shouldn't be deployed until this is fully rolled out for Connector users as the changes in the Zotero client are not backwards-compatible with earlier versions of Connector.

**Comment by dstillman** [comment]
Not sure how much of the save-to-server logic has actually changed, or what we actually supported before, but if I'm at my storage quota, I get a misleading error message that suggests the whole save has failed:

Screenshot 2025-03-28 at 5 03 12 AM

And I get two broken attachments, since the attachment items are created but the file requests fail with 413s, and the attachment items aren't deleted after. I can open a separate issue for this if this isn't new.

**Comment by dstillman** [comment]
But the proper behavior here would be red X for the attachments and automatic DELETE on the failed attachment items, plus ideally a message below about the quota.

**Comment by adomasven** [comment]
> And I get two broken attachments, since the attachment items are created but the file requests fail with 413s, and the attachment items aren't deleted after. I can open a separate issue for this if this isn't new.

Since attachment upload didn't used to work before (everything got attached as links), this is new, but probably doesn't have to hold this PR up.

File: src/common/itemSaver.js [hunk 1]
```diff
@@ -127,64 +124,228 @@ ItemSaver.prototype = {
...
+	},
+	
+	async saveOAAttachment(item, attachmentCallback) {
+		let attachment = item.attachments.find(a => a.isPrimary);
+		try {
+			// Check if we can get an OA PDF from Zotero
+			if (typeof item.hasAlternativeAttachment === "undefined") {
+				// Change line for the primary attachment if we're going to look for OA alternatives
+				if (attachment) {
+					attachment.title = "Searching for Open Access files…";
```
Comment (dstillman) [inline src/common/itemSaver.js:301]: We'll need to localize these.

File: src/common/inject/pageSaving.js [hunk 2]
```diff
@@ -627,6 +598,46 @@ let PageSaving = {
 		
 		var sessionID = this._initSession(translatorID, options);
 		return await this.saveAsWebpage({sessionID, title, snapshot: options.snapshot, resave: options.resave});
+	},
+
+	/**
+	 * Updates the session with the given data.
+	 * @param {Object} data - The data to update the session with.
+	 * @param {String} data.targetId - The target ID
+	 * @param {Boolean} data.resaveFiles - Whether files should be resaved
```
Comment (dstillman) [inline src/common/inject/pageSaving.js:616]: resaveAttachments?

File: src/common/inject/progressWindow_inject.js [hunk 3]
```diff
@@ -56,6 +56,7 @@ if (isTopWindow) {
 	var nextSessionUpdateData;
 	
 	var isReadOnly = false;
+	var isFiledEditableOnly = false;
```
Comment (dstillman) [inline src/common/inject/progressWindow_inject.js:59]: isFilesEditable?

File: src/common/itemSaver.js [hunk 4]
```diff
@@ -127,64 +124,228 @@ ItemSaver.prototype = {
...
+					itemID: item.id
+				});
+			}
+			if (!item.hasAttachmentResolvers) {
+				if (attachment) {
+					attachment.title = Zotero.getString("progressWindow_OA_notFound");
+					attachmentCallback(attachment, false)
+				}
+				return;
+			}
```
Comment (dstillman) [inline src/common/itemSaver.js:315]: I don't think the logic here is right (and I think is just like this because of the original incorrect `HasOAAttachments` endpoint name).

1) If there are no resolvers, we don't need to say anything about OA versions at all — it should just stay on the original title (presumably with the red X).

2) We already show "Open Access PDF" when we're trying the actual download. `hasAttachmentResolvers` should be very quick. 

So I don't think we need the `searching` or `notFound` strings at all?

Comment (adomasven) [reply src/common/itemSaver.js:315]: Right, if there, but it should be mimicking what we did before:
1. If the original translator didn't specify a PDF attachment, we don't display anything unless we find an OA PDF
2. If the original translator does specify a PDF attachment and it fails to load, we replace it with "Searching for Open Access PDFs" provided there are resolvers.
3. If we fail to get an OA PDF, then we show the `failedToGetPDF` string.

Arguably, for 2 maybe we should not be replacing the line for the attachment that failed to download via the browser, and just append a line about search for OA PDFs. And yes, we don't need the `notFound` string.

**Comment by dstillman** [comment]
Regression: Saving a PDF directly shows a "Snapshot" entry below the attachment.

Screenshot 2025-04-02 at 1 43 18 AM

**Comment by dstillman** [comment]
Should saving a PDF directly to the server not work?

Screenshot 2025-04-02 at 1 48 02 AM

**Comment by dstillman** [comment]
The save popup isn't closing automatically when saving to server from https://arxiv.org/abs/2504.00054:

Screenshot 2025-04-02 at 1 50 16 AM

In console:

> Uncaught (in promise) TypeError: Message length exceeded maximum allowed length.  background-worker.js:1 
> Promise.then |   |  
>  | onMessage | @ | browser-polyfill.js:887

**Comment by adomasven** [comment]
> Should saving a PDF directly to the server not work?

It didn't historically work, but we can definitely add this.

**Comment by adomasven** [comment]
Addressed and also some additional fixes for saving to server

**Comment by dstillman** [comment]
Same snapshot failure on any translator page, I think, including https://arxiv.org/abs/2504.00054 above, which was working before.

Screenshot 2025-04-02 at 4 42 12 AM

And there's no snapshot attempt on https://www.zotero.org/, which doesn't have a translator, even though I have the pref enabled.

**Comment by dstillman** [comment]
And an error directly saving the above PDF to server:

Screenshot 2025-04-02 at 5 52 53 AM

Screenshot 2025-04-02 at 5 53 39 AM

**Comment by adomasven** [comment]
Ok, fixed. Found some additional bugs in the bot detection and saving to server code along the way.

**Comment by dstillman** [comment]
I'm still getting the error for the direct PDF save to server in Chrome on ScienceDirect. Expected?

**Comment by adomasven** [comment]
Should be fixed

**Comment by dstillman** [comment]
On https://forums.zotero.org/discussion/123152/feature-request-option-to-disable-automatic-markdown-in-notes, the snapshot is saved from the app rather than the extension.
